### ISSUE TITLE
llmtop10.com: minor issue with menu button on mobile

### ISSUE THREAD

**Issue by mattbit** [OWASP/www-project-top-10-for-large-language-model-applications#110]
Hi, thank you for launching this fantastic initiative. Just wanted to report a minor bug on llmtop10.com — hope this is this the right place.

On mobile or narrow screens, the menu button is not visible. It seems that the button is functional, but the font color matches the background making it not visible:

![current](https://github.com/OWASP/www-project-top-10-for-large-language-model-applications/assets/1101742/afd14d96-6ebe-4b5b-9a8f-9a3bec397b5b)

What I’d expect:
![correct](https://github.com/OWASP/www-project-top-10-for-large-language-model-applications/assets/1101742/b3b26fc8-07d1-4f36-89b8-f54992d6f0eb)

If the website sources are available somewhere I’m happy to open a PR.

**Comment by testgithubsonika** [comment]
this is happening because your phone screen is not sufficient. so you better rotate phone screen in landscape mode or use laptop.

**Comment by testgithubsonika** [comment]
> Hi, thank you for launching this fantastic initiative. Just wanted to report a minor bug on llmtop10.com — hope this is this the right place.
> 
> On mobile or narrow screens, the menu button is not visible. It seems that the button is functional, but the font color matches the background making it not visible:
> 
> ![current](https://user-images.githubusercontent.com/1101742/258045722-afd14d96-6ebe-4b5b-9a8f-9a3bec397b5b.png)
> 
> What I’d expect: ![correct](https://user-images.githubusercontent.com/1101742/258045802-b3b26fc8-07d1-4f36-89b8-f54992d6f0eb.png)
> 
> If the website sources are available somewhere I’m happy to open a PR.
this is happening because your phone screen is not sufficient. so you better rotate phone screen in landscape mode or use laptop.

**Comment by testgithubsonika** [comment]
please assign me if possible

**Comment by testgithubsonika** [comment]
in this issue some changes make in css/js can solve the problem

**Comment by mattbit** [comment]
Closing this as it was fixed with the latest update of llmtop10.com
