### ISSUE TITLE
Wiki Request - FAQ

### ISSUE THREAD

**Issue by GTKlondike** [OWASP/www-project-top-10-for-large-language-model-applications#12]
Per Slack, 
Steve Wilson
  [20 hours ago](https://owasp.slack.com/archives/C05956H7R8R/p1685649407015419?thread_ts=1685648407.415979&cid=C05956H7R8R)
If anyone wants to start an FAQ page on the wiki, that might be a great idea!

**Comment by virtualsteve-star** [comment]
Anyone in the group can start this page.  Permissions are wide open to create new pages on the wiki.

**Comment by eneelou** [comment]
We have covered most FAQ-relevant questions here:
* Why and what we are doing: https://github.com/OWASP/www-project-top-10-for-large-language-model-applications/wiki/Charter
* How success should look like: https://github.com/OWASP/www-project-top-10-for-large-language-model-applications/wiki/Mock-Press-Release

**Comment by virtualsteve-star** [comment]
I think we've covered this for now, and I've just worked with Mike to add an FAQ to the web site.  Closing this for now.
