### ISSUE TITLE
Model DoS Grammar/Spelling

### ISSUE THREAD

**Issue by Bobsimonoff** [OWASP/www-project-top-10-for-large-language-model-applications#147]
An attacker interacts with a LLM in a method 

(change a to an)
An attacker interacts with an LLM in a method 

Sending queries that are unusually resource-consuming, perhaps because they use unusual orthography or sequences.

(somewhat shorter)
Sending unusually resource-consuming queries, perhaps because they use unusual orthography or sequences.

An attacker repeatedly sends multiple requests to a hosted model that are difficult and costly for it to process, leading

(wording improvement?)
An attacker repeatedly sends multiple difficult and costly requests to a hosted model leading 

This flood of inputs puts excessive load on the LLM's resources, 

(add an?)
This flood of inputs puts an excessive load on the LLM's resources,

**Comment by kenhuangus** [comment]
Thanks @Bobsimonoff for the change. Please update the entry directly with your change and do a PR so that I can approve it and keep the track inside the LLM04 entry.

**Comment by Bobsimonoff** [comment]
thanks @kenhuangus   I have never done this before so I hope I did it correctly ... let me know please
