### ISSUE TITLE
Recomend rewording example to not call out a particular company

### ISSUE THREAD

**Issue by Bobsimonoff** [OWASP/www-project-top-10-for-large-language-model-applications#177]
Also add a little clarification

3. Clearly separate and label any external or untrusted content used in prompts passed to the LLM. This allows the model to distinguish influencers like user prompts versus unvalidated external sources. Segregating these input sources may limit the ability of malicious external content to manipulate or inject unintended behavior into the LLM's prompt interpretations. This mitigation alone, however, is easily jailbroken, so must be used in conjunction with other mitigations.

**Comment by leondz** [comment]
Agree, will fix. Thanks for the revised wording.

**Comment by leondz** [comment]
see PR #208
