### ISSUE TITLE
Possible addition to prompt injection "mitigations"

### ISSUE THREAD

**Issue by Bobsimonoff** [OWASP/www-project-top-10-for-large-language-model-applications#178]
The following options will not prevent Prompt Injection, but can help in identifying and resolving problems

1. Utilize LLM monitoring tools that track user prompts and associate them with backend activity including LLM responses. While not a mitigation, this can provide data needed to detect weaknesses and address them.

**Comment by leondz** [comment]
Monitoring for prompt injection is pretty tough, but some monitoring is better than none. Will include recommendation

**Comment by leondz** [comment]
see #207
