### ISSUE TITLE
Clarify the description in LLM02

### ISSUE THREAD

**Issue by mik0w** [OWASP/www-project-top-10-for-large-language-model-applications#191]
**Background**
In the LLM02, the following wording is stated: 
"_The application is vulnerable to **external prompt injection attacks**, which could allow an
attacker to gain privilege` access to a target user's environment_"

**Suggested change**
I assume that what author had in mind was _indirect prompt injection_, I think that the following can be rephrased to: 
"_The application is vulnerable to indirect prompt injection attacks, which could allow an
attacker to gain privilege` access to a target user's environment_"

**Comment by Bobsimonoff** [comment]
There seems to be an extra punctuation in the original and recommended text:    
> privilege ` access...

I assume the replacement text is

- The application is vulnerable to indirect prompt injection attacks, which could allow an attacker to gain privileged access to a target user's environment.

**Comment by mik0w** [comment]
Yeah, I copied it directly from the PDF document - there might have been some kind of encoding conflict, I'm not sure, sorry :)

**Comment by Bobsimonoff** [comment]
No worries at all man! Happy for the good feedback! Thank you

**Comment by kenhuangus** [comment]
Thanks for the comment. I created a RP to change external prompt injection to indirect prompt injection. This issue is closed.
