### ISSUE TITLE
Add early ref for responsible disclosure of Prompt Injection

### ISSUE THREAD

**Issue by leondz** [OWASP/www-project-top-10-for-large-language-model-applications#215]
Was PR #213 

Adds a reference to PromptInjection.md with the original responsible disclosure of prompt injection to OpenAI by Preamble on May 3, 2022, which also contains three potential mitigation techniques. Thank you very much,
-- uart-byte (Jon Cefalu from Preamble, Inc.), prompt injection's discoverer

```
14. [Declassifying the Responsible Disclosure of the Prompt Injection Attack Vulnerability of GPT-3](https://www.preamble.com/prompt-injection-a-critical-vulnerability-in-the-gpt-3-transformer-and-how-we-can-begin-to-solve-it): **Preamble**
```

**Comment by uart-byte** [comment]
Hi Leondz, I wanted to follow up about this PR, and also wanted to mention that Mr. Klondike indicated that we passed the fact check. ✅   Thanks! @leondz

**Comment by leondz** [comment]
Thanks! In PR #236 :)
