### ISSUE TITLE
Need social links on llmtop10 site

### ISSUE THREAD

**Issue by faceplate27** [OWASP/www-project-top-10-for-large-language-model-applications#279]
Hi there. I'd love to have the social links up for LinkedIn, TwitteX, Instagram, YouTube, Spotify and RSS in our header, if possible. Else, footer. I was thinking just greyed images of their app logos.. nothing fancy or flashy.

LinkedIn: https://www.linkedin.com/company/owasp-top-10-for-large-language-model-applications/
X: https://twitter.com/LLM_Top10
Insta: https://www.instagram.com/llmtop10/
YouTube: https://www.youtube.com/@LLMTop10
Spotify: https://open.spotify.com/show/4vTPhIiaVLrQoPoMgcdGBU?si=16899669048e4198
RSS: https://anchor.fm/s/ef87f8e4/podcast/rss

Thanks,

Aubrey

**Comment by faceplate27** [comment]
I have not yet, but I did the other day.. will ask him about this on Monday.

**Comment by mkfnch** [comment]
This has been added into the new WordPress version that @SClinton has built, so I'm closing this here.
![Screenshot 2024-04-30 at 4 56 32 PM](https://github.com/OWASP/www-project-top-10-for-large-language-model-applications/assets/2190981/1d94294c-da09-4fe5-a4cd-e400166056f6)
