### ISSUE TITLE
Migrate the current `llmtop10.com` site to OWASP apex and new hosting/solution

### ISSUE THREAD

**Issue by GangGreenTemperTatum** [OWASP/www-project-top-10-for-large-language-model-applications#280]
Remember, an issue is not the place to ask questions. You can use our [Slack channel](https://github.com/OWASP/www-project-top-10-for-large-language-model-applications/wiki) for that, or you may want to start a discussion on the [Discussion Board](https://github.com/OWASP/www-project-top-10-for-large-language-model-applications/discussions).

### When reporting an issue, please be sure to include the following:
- [X ] Before you open an issue, please check if a similar issue already exists or has been closed before.
- [X] A descriptive title and apply the specific **LLM-0-10** label relative to the entry. See our [available labels](https://github.com/OWASP/www-project-top-10-for-large-language-model-applications/labels).
- [X ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [X ] If the enhancement changes current behavior, reasons why your solution is better
- [X ] What artifact and version of the project you're referencing, and the location (I.E OWASP site, llmtop10.com, repo)
- [X ] The behavior you expect to see, and the actual behavior

#### Steps to Reproduce
-------------------------------------------
NA

#### What happens?
-------------
We currently have multiple problems with the current `llmtop10.com` [site](https://llmtop10.com/), mainly being that it's built on Jekyll which is inconvenient to edit but also difficult to hack. Moving to self-hosted WordPress/Ghost flips that paradigm (easy to edit but also easier to hack) 
- Ownership and limited shared access for multiple devs
- The site is not well portable, difficult to manage and limits management

#### What were you expecting to happen?
----------------------------------
NA

#### Any logs, error output, etc?
----------------------------
NA

#### Any other comments?
-------------------
We will be migrating this under the `owasp.org` umbrella and nesting it within the apex domain as a subdomain
- Subdomain TBC and is currently in voting between core team members
- > re Wordpress simply for manageability by a broader skill set of folks so we can find a balance to both empower more folks, have an approval and publishing workflow, and secure the site through a managed offering.
- The current site (as well as having the domain transferred), will be forwarded to the new destination FQDN
- We should also focus on a publishing for awareness and visibility of changes to the project
- [here](https://owasp.slack.com/archives/C05CM6DUZ1D/p1711735525562389) in **#team-llm-core** Slack post link (if relevant)

#### What versions of hardware and software are you using?
----------------------------------------
NA

**Comment by mkfnch** [comment]
This task should probably be owned by @SClinton. He's the one building the new site on WordPress- not me.
