### ISSUE TITLE
Add five entries to core team member list on genai.owasp.org

### ISSUE THREAD

**Issue by Setotet** [OWASP/www-project-top-10-for-large-language-model-applications#434]
#### Steps to Reproduce
-------------------------------------------
Go to https://genai.owasp.org/contributors/

#### What happens?
-------------
Tetsuo Seto, Aruneesh Salhotra,  Vinnie Giarrusso, Bryan Nakayama, Aditya Rana are missing.

#### What were you expecting to happen?
----------------------------------
Tetsuo Seto, Aruneesh Salhotra,  Vinnie Giarrusso, Bryan Nakayama, Aditya Rana are listed as follows:

Name: Tetsuo Seto
Role: Expert
Organization:
Personal Links:  [Github](https://github.com/tetsuoseto)

Name: Aruneesh Salhotra
Role: Expert
Organization: SNM Consulting Inc
Personal Links: [LinkedIn](https://www.linkedin.com/in/aruneeshsalhotra)

Name: Vinnie Giarrusso
Role: Expert
Organization: [Twilio](https://www.twilio.com/)
Personal Links:  [Github](https://github.com/vingiarrusso), [LinkedIn](https://www.linkedin.com/in/vinniegiarrusso)

Name: Bryan Nakayama
Role: Expert
Organization:
Personal Links: [LinkedIn](https://www.linkedin.com/in/bryannakayama/), [Bio](https://www.bnakayama.com/)

Name: Aditya Rana
Role: Expert
Organization:
Personal Links: [LinkedIn](https://www.linkedin.com/in/adi1ya/), [X](https://x.com/Green_terminals)

#### Any logs, error output, etc?
----------------------------
none

#### Any other comments?
-------------------
none

#### What versions of hardware and software are you using?
----------------------------------------
**Operating System: MacOS
**Browser:** 
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by GangGreenTemperTatum** [comment]
Thanks for raising @Setotet ! Will do this today 👍

**Comment by Setotet** [comment]
Name: Bryan Nakayama
Role: Expert
Organization:
Personal Links: [LinkedIn](https://www.linkedin.com/in/bryannakayama/), [Bio](https://www.bnakayama.com/)

**Comment by GangGreenTemperTatum** [comment]
done ✅

**Comment by Setotet** [comment]
Regression
