### ISSUE TITLE
OWASP Top 10 LLM PDFs have broken web links

### ISSUE THREAD

**Issue by skamkar** [OWASP/www-project-top-10-for-large-language-model-applications#476]
[Version 1.1.0](https://owasp.org/www-project-top-10-for-large-language-model-applications/assets/PDF/OWASP-Top-10-for-LLMs-2023-v1_1.pdf) redirects to 404.

This is true for [1.0.1](https://owasp.org/www-project-top-10-for-large-language-model-applications/assets/PDF/OWASP-Top-10-for-LLMs-2023-v1_0_1.pdf), [1.0.0](https://owasp.org/www-project-top-10-for-large-language-model-applications/assets/PDF/OWASP-Top-10-for-LLMs-2023-v1_0.pdf), [0.9.0](https://owasp.org/www-project-top-10-for-large-language-model-applications/assets/PDF/OWASP-Top-10-for-LLMs-2023-v09.pdf), and probably other archive versions as well.

I was going to the /assets folder to retrieve, but a PDF folder doesn't appear to exist on the main branch.

**Comment by GangGreenTemperTatum** [comment]
hey @skamkar , thanks for flagging!

i reverted https://github.com/OWASP/www-project-top-10-for-large-language-model-applications/pull/470, please can you re-test and confirm in a few minutes? [build](https://github.com/OWASP/www-project-top-10-for-large-language-model-applications/actions/runs/11875561417) shouldnt take long. tyia!

**Comment by skamkar** [comment]
yes, works now. thanks much.
