### ISSUE TITLE
Please don't use `:` as part of filename. Windows unable handle this character.

### ISSUE THREAD

**Issue by doggy8088** [OWASP/www-project-top-10-for-large-language-model-applications#517]
There is a `data_gathering/mappings/ISO20547-4:2020.md` file. The filename contains a `:` character which is unable to handle in Windows. For Windows users, they will not able to checkout files during `git clone`.

```sh
git clone https://github.com/OWASP/www-project-top-10-for-large-language-model-applications.git
```

![image](https://github.com/user-attachments/assets/ee02dd8e-5d0d-4635-8b11-35eda0566a11)

**Comment by doggy8088** [comment]
Thanks, @GangGreenTemperTatum 👍

**Comment by GangGreenTemperTatum** [comment]
> Thanks, @GangGreenTemperTatum 👍

thanks for raising and taking the time to contribute here @doggy8088 !
