### ISSUE TITLE
Home page typo

### ISSUE THREAD

**Issue by utalmighty** [OWASP/www-project-top-10-for-large-language-model-applications#518]
Remember, an issue is not the place to ask questions. You can use our [Slack channel](https://github.com/OWASP/www-project-top-10-for-large-language-model-applications/wiki) for that, or you may want to consult the following Slack channels:

- [#project-top10-for-llm](https://owasp.slack.com/archives/C05956H7R8R)
- [#team-llm-web](https://owasp.slack.com/archives/C06RXVCQB1C)
- [#team-llm_diagrams_and_visuals](https://owasp.slack.com/archives/C05L7TW8VCY)
- Each vulnerabilities has its own dedicated Slack channel for discussions in the format of `#team-llm0X`, I.E ([#team-llm03_data_and_model_poisoning](https://owasp.slack.com/archives/C05F7JWFYBU))

### When reporting an issue, please be sure to include the following:
- [x] Before you open an issue, please check if a similar issue already exists or has been closed before.
- [x] A descriptive title and apply the specific **LLM-0-10** label relative to the entry. See our [available labels](https://github.com/OWASP/www-project-top-10-for-large-language-model-applications/labels).
- [x] The behavior you expect to see, and the actual behavior

#### Steps to Reproduce
-------------------------------------------
1. Visit link [OWASP top 10 LLM] (https://owasp.org/www-project-top-10-for-large-language-model-applications/#:~:text=Become%20a%20Project%20Suppoter%20or%20Sponsor%20Sponsorship)

# Expected
Become a Project **Supporter** or Sponsor Sponsorship

# Actual
Become a Project **Suppoter** or Sponsor Sponsorship

**Comment by GangGreenTemperTatum** [comment]
Fixed #519
